import {
  Organization,
  Pod,
  Profile,
  Checkin,
  Update,
  Blocker,
  Kudos,
  Sprint,
  NotificationItem,
  GoogleChatSettings,
  AuditLog,
} from '../types/database';

export const INITIAL_ORGANIZATION: Organization = {
  id: 'org-maple-01',
  name: 'Maple Learning Solutions',
  slug: 'maple-learning-solutions',
  timezone: 'America/Toronto',
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-08-20T00:00:00Z',
};

export const INITIAL_PODS: Pod[] = [
  {
    id: 'pod-web-sales',
    organization_id: 'org-maple-01',
    name: 'Web & Sales',
    description: 'Web development, client platforms, revenue initiatives, and sales conversion workflows.',
    manager_id: 'prof-renuka',
    status: 'active',
    members_count: 5,
    participation_rate: 94,
    active_blockers_count: 1,
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'pod-marketing',
    organization_id: 'org-maple-01',
    name: 'Marketing',
    description: 'Brand awareness, digital growth, social outreach, and content campaigns.',
    manager_id: 'prof-nithin',
    status: 'active',
    members_count: 3,
    participation_rate: 90,
    active_blockers_count: 0,
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'pod-elearning',
    organization_id: 'org-maple-01',
    name: 'eLearning',
    description: 'Interactive curriculum development, instructional design, and LMS courseware.',
    manager_id: 'prof-dhana',
    status: 'active',
    members_count: 8,
    participation_rate: 88,
    active_blockers_count: 1,
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'pod-hr',
    organization_id: 'org-maple-01',
    name: 'HR Operations',
    description: 'Talent acquisition, employee experience, policy compliance, and internal operations.',
    manager_id: 'prof-swetha',
    status: 'active',
    members_count: 2,
    participation_rate: 100,
    active_blockers_count: 0,
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
];

// Complete canonical organization roster mapped directly to org chart
export const INITIAL_PROFILES: Profile[] = [
  // ============================================================================
  // 1. EXECUTIVE LEADERSHIP & ADMINS (Access to all Pods)
  // ============================================================================
  {
    id: 'prof-admin',
    organization_id: 'org-maple-01',
    full_name: 'Maple Edge Admin',
    email: 'info@maplelearningsolutions.com',
    role: 'admin',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-sandeep',
    organization_id: 'org-maple-01',
    full_name: 'Sandeep M',
    email: 'sandeep@maplelearningsolutions.com',
    role: 'admin',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-raj',
    organization_id: 'org-maple-01',
    full_name: 'Raj Ayyanar',
    email: 'raj.ayyanar@maplelearningsolutions.com',
    role: 'admin',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-krishna',
    organization_id: 'org-maple-01',
    full_name: 'Krishna Sunkara',
    email: 'krishna@maplelearningsolutions.com',
    role: 'admin',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-rathish',
    organization_id: 'org-maple-01',
    full_name: 'Rathish Rajendran',
    email: 'rathish.rajendran@maplelearningsolutions.com',
    role: 'admin',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },

  // ============================================================================
  // 2. POD 1: WEB & SALES (Lead: Renuka Gorugantu)
  // ============================================================================
  {
    id: 'prof-renuka',
    organization_id: 'org-maple-01',
    full_name: 'Renuka Gorugantu',
    email: 'renuka@maplelearningsolutions.com',
    role: 'manager',
    pod_id: 'pod-web-sales',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-nithin',
    organization_id: 'org-maple-01',
    full_name: 'Nithin Guggilla',
    email: 'nithin@maplelearningsolutions.com',
    role: 'manager', // Lead for Marketing, also AI Developer for Web & Sales
    pod_id: 'pod-web-sales',
    manager_id: 'prof-renuka',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-raghavi',
    organization_id: 'org-maple-01',
    full_name: 'Raghavi Jammula',
    email: 'raghavi@maplelearningsolutions.com',
    role: 'member',
    pod_id: 'pod-web-sales',
    manager_id: 'prof-renuka',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-harshika',
    organization_id: 'org-maple-01',
    full_name: 'Harshika Netha',
    email: 'harshika@maplelearningsolutions.com',
    role: 'member',
    pod_id: 'pod-web-sales',
    manager_id: 'prof-renuka',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-susan',
    organization_id: 'org-maple-01',
    full_name: 'Susan Vijaya',
    email: 'susan@maplelearningsolutions.com',
    role: 'member',
    pod_id: 'pod-web-sales',
    manager_id: 'prof-renuka',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },

  // ============================================================================
  // 3. POD 2: MARKETING (Lead: Nithin Guggilla)
  // ============================================================================
  {
    id: 'prof-abhishek',
    organization_id: 'org-maple-01',
    full_name: 'Abhishek Guna',
    email: 'abhishek@maplelearningsolutions.com',
    role: 'member',
    pod_id: 'pod-marketing',
    manager_id: 'prof-nithin',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },

  // ============================================================================
  // 4. POD 3: ELEARNING (Lead: Dhana Sekhar)
  // ============================================================================
  {
    id: 'prof-dhana',
    organization_id: 'org-maple-01',
    full_name: 'Dhana Sekhar',
    email: 'dhana@maplelearningsolutions.com',
    role: 'manager',
    pod_id: 'pod-elearning',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-christeena',
    organization_id: 'org-maple-01',
    full_name: 'Christeena George',
    email: 'christeena@maplelearningsolutions.com',
    role: 'member',
    pod_id: 'pod-elearning',
    manager_id: 'prof-dhana',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-malavika',
    organization_id: 'org-maple-01',
    full_name: 'Malavika Koraganti',
    email: 'malavika@maplelearningsolutions.com',
    role: 'member',
    pod_id: 'pod-elearning',
    manager_id: 'prof-dhana',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-pratap',
    organization_id: 'org-maple-01',
    full_name: 'Pratap Rudra',
    email: 'pratap@maplelearningsolutions.com',
    role: 'member',
    pod_id: 'pod-elearning',
    manager_id: 'prof-dhana',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-navyasree',
    organization_id: 'org-maple-01',
    full_name: 'Navyasree Nuthangi',
    email: 'navyasree@maplelearningsolutions.com',
    role: 'member',
    pod_id: 'pod-elearning',
    manager_id: 'prof-dhana',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-varsha',
    organization_id: 'org-maple-01',
    full_name: 'Varsha chhanganiji',
    email: 'varsha@maplelearningsolutions.com',
    role: 'member',
    pod_id: 'pod-elearning',
    manager_id: 'prof-dhana',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-swathi',
    organization_id: 'org-maple-01',
    full_name: 'Swathi Thoranala',
    email: 'swathi@maplelearningsolutions.com',
    role: 'member',
    pod_id: 'pod-elearning',
    manager_id: 'prof-dhana',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prof-bhanu',
    organization_id: 'org-maple-01',
    full_name: 'Bhanu Reddy Shetty',
    email: 'bhanu.reddy@maplelearningsolutions.com',
    role: 'member',
    pod_id: 'pod-elearning',
    manager_id: 'prof-dhana',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },

  // ============================================================================
  // 5. POD 4: HR OPERATIONS (Lead: Swetha N)
  // ============================================================================
  {
    id: 'prof-swetha',
    organization_id: 'org-maple-01',
    full_name: 'Swetha N',
    email: 'swetha@maplelearningsolutions.com',
    role: 'manager',
    pod_id: 'pod-hr',
    timezone: 'America/Toronto',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=128&auto=format&fit=crop&q=80',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  },
];

export const INITIAL_CHECKIN: Checkin = {
  id: 'chk-maple-daily',
  organization_id: 'org-maple-01',
  name: 'Daily Standup Check-in',
  description: 'Asynchronous morning coordination check-in across all Maple Learning Solutions pods.',
  frequency: 'daily',
  active: true,
  start_time: '09:00',
  deadline_time: '11:00',
  reminder_time: '09:30',
  days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  timezone: 'America/Toronto',
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-08-20T00:00:00Z',
  questions: [
    {
      id: 'q-1',
      checkin_id: 'chk-maple-daily',
      question: 'What did you complete yesterday?',
      question_type: 'text',
      required: true,
      sort_order: 1,
      created_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'q-2',
      checkin_id: 'chk-maple-daily',
      question: 'What are you working on today?',
      question_type: 'text',
      required: true,
      sort_order: 2,
      created_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'q-3',
      checkin_id: 'chk-maple-daily',
      question: 'Do you have any blockers or require team support?',
      question_type: 'boolean',
      required: false,
      sort_order: 3,
      created_at: '2026-01-01T00:00:00Z',
    },
  ],
};

const todayStr = new Date().toISOString().split('T')[0];

export const INITIAL_UPDATES: Update[] = [];

export const INITIAL_BLOCKERS: Blocker[] = [];

export const INITIAL_KUDOS: Kudos[] = [];

export const INITIAL_SPRINT: Sprint = {
  id: 'spr-56',
  organization_id: 'org-maple-01',
  name: 'Sprint 56 — Platform Operations',
  description: 'Current active operational sprint for Maple Learning Solutions.',
  start_date: '2026-08-11',
  end_date: '2026-08-24',
  status: 'active',
  created_at: '2026-08-10T00:00:00Z',
  updated_at: '2026-08-20T00:00:00Z',
  total_updates: 0,
  participation_rate: 0,
  blockers_count: 0,
  resolved_blockers_count: 0,
  kudos_count: 0,
};

export const INITIAL_GOOGLE_CHAT_SETTINGS: GoogleChatSettings = {
  id: 'gchat-maple-01',
  organization_id: 'org-maple-01',
  enabled: true,
  space_id: 'spaces/AAQA8ijHd80',
  space_name: 'Maple Team Updates',
  webhook_url: 'https://chat.googleapis.com/v1/spaces/AAQA8ijHd80/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=vR_WlFMQiHtcfTFfa2B5qfy6y14GpyXdIczanj0q5w0',
  report_time: '10:30',
  daily_reports: true,
  weekly_reports: true,
  sprint_reports: true,
  blocker_alerts: true,
  kudos_alerts: true,
  created_at: '2026-01-10T00:00:00Z',
  updated_at: '2026-08-20T00:00:00Z',
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    organization_id: 'org-maple-01',
    profile_id: 'prof-renuka',
    type: 'reminder',
    title: 'Daily Standup Reminder',
    message: 'Good morning! Please log your daily standup update for Web & Sales.',
    read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
];

// Aliases for dataStore compatibility
export const INITIAL_ORG = INITIAL_ORGANIZATION;
export const INITIAL_GOOGLE_CHAT = INITIAL_GOOGLE_CHAT_SETTINGS;
export const INITIAL_AUDIT_LOGS: AuditLog[] = [];
