// ==============================================================================
// MapleBot: Declared Company Holidays & Sample Planned Leaves (2026)
// Complete Calendar across Q1, Q2, Q3, Q4 / H1, H2 / Full Year
// ==============================================================================

import { CompanyHoliday, LeaveRequest } from '../types/leave';

export const INITIAL_COMPANY_HOLIDAYS_2026: CompanyHoliday[] = [
  // --- Q1 / H1 2026 ---
  {
    id: 'hol-01',
    organization_id: 'org-maple-01',
    name: "New Year's Day",
    date: '2026-01-01',
    day_of_week: 'Thursday',
    type: 'mandatory',
    quarter: 'Q1',
    half_year: 'H1',
    year: 2026,
    description: 'First day of the new calendar year celebration.',
  },
  {
    id: 'hol-02',
    organization_id: 'org-maple-01',
    name: 'Republic Day',
    date: '2026-01-26',
    day_of_week: 'Monday',
    type: 'mandatory',
    quarter: 'Q1',
    half_year: 'H1',
    year: 2026,
    description: 'National holiday commemorating the Constitution of India.',
  },
  {
    id: 'hol-03',
    organization_id: 'org-maple-01',
    name: 'Maha Shivaratri',
    date: '2026-02-17',
    day_of_week: 'Tuesday',
    type: 'optional',
    quarter: 'Q1',
    half_year: 'H1',
    year: 2026,
    description: 'Optional floating holiday.',
  },
  {
    id: 'hol-04',
    organization_id: 'org-maple-01',
    name: 'Holi (Festival of Colors)',
    date: '2026-03-25',
    day_of_week: 'Wednesday',
    type: 'mandatory',
    quarter: 'Q1',
    half_year: 'H1',
    year: 2026,
    description: 'Celebration of spring and colors.',
  },

  // --- Q2 / H1 2026 ---
  {
    id: 'hol-05',
    organization_id: 'org-maple-01',
    name: 'Good Friday',
    date: '2026-04-03',
    day_of_week: 'Friday',
    type: 'mandatory',
    quarter: 'Q2',
    half_year: 'H1',
    year: 2026,
    description: 'Christian holiday observing the crucifixion of Jesus.',
  },
  {
    id: 'hol-06',
    organization_id: 'org-maple-01',
    name: 'Eid al-Fitr',
    date: '2026-04-10',
    day_of_week: 'Friday',
    type: 'mandatory',
    quarter: 'Q2',
    half_year: 'H1',
    year: 2026,
    description: 'Islamic festival marking the end of Ramadan.',
  },
  {
    id: 'hol-07',
    organization_id: 'org-maple-01',
    name: 'International Workers Day',
    date: '2026-05-01',
    day_of_week: 'Friday',
    type: 'mandatory',
    quarter: 'Q2',
    half_year: 'H1',
    year: 2026,
    description: 'Global Labor and Workers Solidarity Day.',
  },
  {
    id: 'hol-08',
    organization_id: 'org-maple-01',
    name: 'Bakrid / Eid al-Adha',
    date: '2026-06-17',
    day_of_week: 'Wednesday',
    type: 'optional',
    quarter: 'Q2',
    half_year: 'H1',
    year: 2026,
    description: 'Feast of the Sacrifice optional holiday.',
  },

  // --- Q3 / H2 2026 ---
  {
    id: 'hol-09',
    organization_id: 'org-maple-01',
    name: 'Independence Day',
    date: '2026-08-15',
    day_of_week: 'Saturday',
    type: 'mandatory',
    quarter: 'Q3',
    half_year: 'H2',
    year: 2026,
    description: 'National Independence Day celebration.',
  },
  {
    id: 'hol-10',
    organization_id: 'org-maple-01',
    name: 'Raksha Bandhan',
    date: '2026-08-28',
    day_of_week: 'Friday',
    type: 'optional',
    quarter: 'Q3',
    half_year: 'H2',
    year: 2026,
    description: 'Optional floating festive holiday.',
  },
  {
    id: 'hol-11',
    organization_id: 'org-maple-01',
    name: 'Ganesh Chaturthi',
    date: '2026-09-07',
    day_of_week: 'Monday',
    type: 'mandatory',
    quarter: 'Q3',
    half_year: 'H2',
    year: 2026,
    description: 'Auspicious festival celebrating Lord Ganesha.',
  },
  {
    id: 'hol-12',
    organization_id: 'org-maple-01',
    name: 'Milad-un-Nabi',
    date: '2026-09-24',
    day_of_week: 'Thursday',
    type: 'optional',
    quarter: 'Q3',
    half_year: 'H2',
    year: 2026,
    description: 'Prophet Muhammad birthday optional holiday.',
  },

  // --- Q4 / H2 2026 ---
  {
    id: 'hol-13',
    organization_id: 'org-maple-01',
    name: 'Mahatma Gandhi Jayanti',
    date: '2026-10-02',
    day_of_week: 'Friday',
    type: 'mandatory',
    quarter: 'Q4',
    half_year: 'H2',
    year: 2026,
    description: 'Birthday of Mahatma Gandhi (National Holiday).',
  },
  {
    id: 'hol-14',
    organization_id: 'org-maple-01',
    name: 'Dussehra / Vijayadashami',
    date: '2026-10-20',
    day_of_week: 'Tuesday',
    type: 'mandatory',
    quarter: 'Q4',
    half_year: 'H2',
    year: 2026,
    description: 'Victory of Good over Evil festive holiday.',
  },
  {
    id: 'hol-15',
    organization_id: 'org-maple-01',
    name: 'Diwali / Deepavali',
    date: '2026-11-08',
    day_of_week: 'Sunday',
    type: 'mandatory',
    quarter: 'Q4',
    half_year: 'H2',
    year: 2026,
    description: 'Festival of Lights primary celebration.',
  },
  {
    id: 'hol-16',
    organization_id: 'org-maple-01',
    name: 'Guru Nanak Jayanti',
    date: '2026-11-24',
    day_of_week: 'Tuesday',
    type: 'optional',
    quarter: 'Q4',
    half_year: 'H2',
    year: 2026,
    description: 'Birth anniversary of Guru Nanak Dev Ji.',
  },
  {
    id: 'hol-17',
    organization_id: 'org-maple-01',
    name: 'Christmas Day',
    date: '2026-12-25',
    day_of_week: 'Friday',
    type: 'mandatory',
    quarter: 'Q4',
    half_year: 'H2',
    year: 2026,
    description: 'Annual Christian festival celebrating the birth of Jesus Christ.',
  },
];

export const INITIAL_PLANNED_LEAVES: LeaveRequest[] = [];
