import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://nvbxkeouibmxuyxqiwua.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52YnhrZW91aWJteHV5eHFpd3VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcxOTk4MzcsImV4cCI6MjEwMjc3NTgzN30.bSz0vzQ7RXkZ312eszWzOrd2f93EW8J5lqNonAJ6Q-U';

const supabase = createClient(supabaseUrl, supabaseAnonKey);

const ALL_UPDATES_TO_SYNC = [
  // ==========================================
  // THURSDAY, AUGUST 20, 2026
  // ==========================================
  {
    profile_id: 'prof-varsha',
    pod_id: 'pod-elearning',
    update_date: '2026-08-20',
    yesterday: 'yesterday i worked upon the section-4 & section-5 for BHA and for DASHVERSE took a kick off call of the project the series which is allocated and then worked on the assets and the script of the EP-10 which is to be delivered on 20.08.26',
    today: 'today i have worked upon the DASHVERSE project  EP-10 anchor images had the interns on call so that they can understand thjw workflow better and help in the coming episodes for the anchor images and then will move ahead with the animations of the episode will keep them in call here as well for better understanding . once animations done will send it to dhana for editing and deliver by 8:30 pm today .',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-renuka',
    pod_id: 'pod-web-sales',
    update_date: '2026-08-20',
    yesterday: '1. Sent 120 emails to the lms companies.\n2. connected with pod members on tasks and requirements.',
    today: 'Worked on the MapleBot application, including landing page, auth flow, and database models.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 90,
  },
  {
    profile_id: 'prof-nithin',
    pod_id: 'pod-marketing',
    update_date: '2026-08-20',
    yesterday: 'Connected with interns on Trello guidance on how to create articles and content outlines.',
    today: 'Post article in medium and substack from Info@maple. Plan and prepare marketing collateral.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 80,
  },
  {
    profile_id: 'prof-swetha',
    pod_id: 'pod-hr',
    update_date: '2026-08-20',
    yesterday: 'HR Tracker: I have created and updated the HR Tracker with all candidates and team roster details.',
    today: 'Worked on Dhana’s offer letter. The process is taking some time and will finalize today.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-raghavi',
    pod_id: 'pod-web-sales',
    update_date: '2026-08-20',
    yesterday: '1. Apollo.io\nWorked on lead generation and contact extraction for sales pipeline.',
    today: '1. Apollo.io\nWorked on lead generation and contact extraction for enterprise LMS outreach.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-harshika',
    pod_id: 'pod-web-sales',
    update_date: '2026-08-20',
    yesterday: 'Posted articles on both Substack and Medium, Learned Git commands and worked on Maple intranet.',
    today: 'Published articles on Medium and Substack 30 minutes.\nWorked on MapleBot application features.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-malavika',
    pod_id: 'pod-elearning',
    update_date: '2026-08-20',
    yesterday: 'Yesterday i was on Leave.',
    today: 'Today i connected with Dhana to discuss Joyalukkas Course01: M1 deliverables.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 75,
  },
  {
    profile_id: 'prof-navyasree',
    pod_id: 'pod-elearning',
    update_date: '2026-08-20',
    yesterday: 'BHA Sections 3 & 4: Completed the required changes for Section 3 and initiated Section 4 design.',
    today: 'BHA Section 4: Continue working on pending changes and Section 5 storyboard.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 80,
  },
  {
    profile_id: 'prof-swathi',
    pod_id: 'pod-elearning',
    update_date: '2026-08-20',
    yesterday: 'I have attended daily training session, then attended two client calls regarding Storyline animations.',
    today: 'Today attended 4 meets and built Storyline interactive assessment templates.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 80,
  },
  {
    profile_id: 'prof-bhanu',
    pod_id: 'pod-elearning',
    update_date: '2026-08-20',
    yesterday: 'I completed the storyline assignment and worked on rise assignment.',
    today: 'completed rise assignment and worked on internal project - 2 storyline modules.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 80,
  },

  // ==========================================
  // FRIDAY, AUGUST 21, 2026
  // ==========================================
  {
    profile_id: 'prof-malavika',
    pod_id: 'pod-elearning',
    update_date: '2026-08-21',
    yesterday: 'i have connected with Dhana to discuss Joyalukkas Course01: M1 deliverables.',
    today: 'Joyalukkas Course01: M1 feedback changes and Course 02 storyboard review.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-navyasree',
    pod_id: 'pod-elearning',
    update_date: '2026-08-21',
    yesterday: 'BHA Project 1 -Section 4 and Section 5: I have worked on the Storyline animations.',
    today: 'BHA Project 1 – Sections 4, 5 & 6: Work on the Storyline interactions and asset placement.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-christeena',
    pod_id: 'pod-elearning',
    update_date: '2026-08-21',
    yesterday: 'Coordinated with Pratap and the vendor regarding the BHA P2 deliverables.',
    today: 'update all the project trackers and resource allocation details for next week sprint.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-harshika',
    pod_id: 'pod-web-sales',
    update_date: '2026-08-21',
    yesterday: 'Posted articles on both substack and medium - 30 minutes, worked on intranet homepage.',
    today: 'Continue to work Maple intranet homepage, post articles on substack and medium.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-nithin',
    pod_id: 'pod-marketing',
    update_date: '2026-08-21',
    yesterday: 'Connected with interns on Trello guidance on how to create articles and templates.',
    today: 'Post article in medium and substack from Info@maple. Plan and prepare outreach.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-raghavi',
    pod_id: 'pod-web-sales',
    update_date: '2026-08-21',
    yesterday: '1. Apollo.io\nWorked on lead generation and contact extraction for sales pipeline.',
    today: '1. Apollo.io\nWorked on lead generation and contact extraction for enterprise accounts.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-swetha',
    pod_id: 'pod-hr',
    update_date: '2026-08-21',
    yesterday: 'Finalized offer letters and updated the candidate tracking sheet.',
    today: 'Employee attendance review, leave policies update, and HR operations documentation.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 90,
  },
  {
    profile_id: 'prof-abhishek',
    pod_id: 'pod-hr',
    update_date: '2026-08-21',
    yesterday: 'Onboarding documentation checklist and orientation support.',
    today: 'Assisting HR operations with candidate communication and profile verification.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-pratap',
    pod_id: 'pod-elearning',
    update_date: '2026-08-21',
    yesterday: 'BHA Project 1: Section 3 illustration adjustments and asset delivery.',
    today: 'BHA-P1-Sec-4 illustration prep and asset pipeline setup.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-varsha',
    pod_id: 'pod-elearning',
    update_date: '2026-08-21',
    yesterday: 'DASHVERSE EP-10 animation frames and character assets.',
    today: 'Dashverse EP-10 final animation render and hand-off to Dhana for video audio cut.',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 90,
  },

  // ==========================================
  // MONDAY, AUGUST 24, 2026 (TODAY)
  // ==========================================
  {
    profile_id: 'prof-pratap',
    pod_id: 'pod-elearning',
    update_date: '2026-08-24',
    yesterday: 'BHA-P1-Sec-4 - 15 Illustrations completed (4 hours)',
    today: 'BHA-P1-Sec-4 remaining illustrations and asset alignment (4 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-varsha',
    pod_id: 'pod-elearning',
    update_date: '2026-08-24',
    yesterday: 'Worked on Episode 10, edits, coordinated the final handover with Dhana (3.5 hours)',
    today: 'today i will be working on Dashverse reviews that we may receive from client and Episode 11 prep (4 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-renuka',
    pod_id: 'pod-web-sales',
    update_date: '2026-08-24',
    yesterday: '* Worked on the MapleBot application, including the landing page and report exports (4 hours)',
    today: '1. Need to send proposals to the projects. (1:30-2 hours)\n2. Connect with client on platform customization (2 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 90,
  },
  {
    profile_id: 'prof-harshika',
    pod_id: 'pod-web-sales',
    update_date: '2026-08-24',
    yesterday: 'Published articles on Medium and Substack and worked on redesign of intranet (3.5 hours)',
    today: 'Publish articles on Medium and Substack 30 mins and complete layout styling for client portal (3.5 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-raghavi',
    pod_id: 'pod-web-sales',
    update_date: '2026-08-24',
    yesterday: 'Extracted 113 contacts from Apollo.io for lead generation. Worked on enrichment (4 hours)',
    today: 'Extract contacts from Apollo.io. Import the extracted contacts to CRM and launch email sequences (4 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-navyasree',
    pod_id: 'pod-elearning',
    update_date: '2026-08-24',
    yesterday: 'BHA Project 1: Section 5 Feedback Discussion with Pratap, Susan, and Dhana (3 hours)',
    today: "Today's Focus: BHA Project 1 – Sections 4, 5 & 6: Work on the Storyline interactions and timing (4 hours)",
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-malavika',
    pod_id: 'pod-elearning',
    update_date: '2026-08-24',
    yesterday: 'Joyalukkas course01: M1 - i have worked on course01: client review changes (3.5 hours)',
    today: 'Joyalukkas course01: M1 & M2 feedback changes and audio sync (4 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-nithin',
    pod_id: 'pod-marketing',
    update_date: '2026-08-24',
    yesterday: 'Prepared social media campaign graphics and reviewed intern blog submissions (3.5 hours)',
    today: 'Publish Medium/Substack articles from Info@maple, execute LinkedIn outreach, and coordinate marketing pod deliverables (4 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 90,
  },
  {
    profile_id: 'prof-swetha',
    pod_id: 'pod-hr',
    update_date: '2026-08-24',
    yesterday: 'Updated HR Tracker, candidate screening pipelines, and employee attendance logs (3 hours)',
    today: 'Coordinate new joinee documentation, process compliance records, and manage HR operations reviews (4 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 90,
  },
  {
    profile_id: 'prof-abhishek',
    pod_id: 'pod-hr',
    update_date: '2026-08-24',
    yesterday: 'Candidate document verification and HR portal data entries (3 hours)',
    today: 'Assist Swetha with HR compliance records and support marketing pod asset scheduling (3.5 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-christeena',
    pod_id: 'pod-elearning',
    update_date: '2026-08-24',
    yesterday: 'BHA P2 tracker reconciliation and resource scheduling for sprint (3 hours)',
    today: 'Instructional design QA for Joyalukkas modules and BHA section reviews with Dhana (4 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-swathi',
    pod_id: 'pod-elearning',
    update_date: '2026-08-24',
    yesterday: 'Storyline interaction modules building and client feedback review (3.5 hours)',
    today: 'BHA courseware slide animations and interactive quiz configuration (4 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-bhanu',
    pod_id: 'pod-elearning',
    update_date: '2026-08-24',
    yesterday: 'Storyline asset layout and Rise assessments testing (3 hours)',
    today: 'Internal training module 2 production and storyline interactions (4 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
  {
    profile_id: 'prof-dhana',
    pod_id: 'pod-elearning',
    update_date: '2026-08-24',
    yesterday: 'Sprint 56 review calls, Joyalukkas milestone checks, and Dashverse cut (4 hours)',
    today: 'eLearning pod deliverable sign-offs, Dashverse video rendering, and sprint tracking (4.5 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 90,
  },
  {
    profile_id: 'prof-susan',
    pod_id: 'pod-web-sales',
    update_date: '2026-08-24',
    yesterday: 'LMS prospect research and enterprise client email campaign setup (3 hours)',
    today: 'Follow up with inbound leads, prepare proposal decks, and CRM updates (4 hours)',
    has_blocker: false,
    status: 'on_track',
    progress_percent: 85,
  },
];

async function syncAll() {
  console.log(`Starting synchronization of ${ALL_UPDATES_TO_SYNC.length} standup records into Supabase...`);

  let successCount = 0;
  for (const upd of ALL_UPDATES_TO_SYNC) {
    const id = `upd-${upd.profile_id}-${upd.update_date}`;
    const now = new Date(`${upd.update_date}T10:00:00Z`).toISOString();

    const { error } = await supabase.from('updates').upsert({
      organization_id: 'org-maple-01',
      checkin_id: 'chk-maple-daily',
      profile_id: upd.profile_id,
      pod_id: upd.pod_id,
      update_date: upd.update_date,
      yesterday: upd.yesterday,
      today: upd.today,
      has_blocker: upd.has_blocker,
      status: upd.status,
      priority: 'high',
      progress_percent: upd.progress_percent,
      submitted_at: now,
      updated_at: now,
    }, { onConflict: 'profile_id,update_date' });

    if (error) {
      console.error(`❌ Failed to sync ${upd.profile_id} on ${upd.update_date}:`, error.message);
    } else {
      successCount++;
      console.log(`✅ Synced: ${upd.profile_id} [${upd.update_date}]`);
    }
  }

  console.log(`\n🎉 Successfully synced ${successCount} of ${ALL_UPDATES_TO_SYNC.length} records!`);
}

syncAll();
